#!/usr/bin/env python3
"""
Bengali TTS Recording Flask Application - Modern Studio Edition

Web-based audio recorder for collecting voice samples.
Features:
- Modern UI with real-time waveform visualization
- Real-time audio quality checks
- Prompt navigation and status tracking
- Re-record functionality for previous recordings
- Metadata management
- Optimized for training: 22kHz mono 16-bit
"""

import os
import csv
import json
import wave
import glob
import subprocess
import tempfile
from datetime import datetime
from flask import Flask, request, jsonify, render_template, send_from_directory

app = Flask(__name__)

# Configuration
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_DIR = os.path.join(BASE_DIR, 'dataset')
RECORDINGS_DIR = os.path.join(DATASET_DIR, 'recordings')

# Use optimized dataset prompts by default (generated by optimize_dataset.py)
OPTIMIZED_PROMPTS_FILE = os.path.join(BASE_DIR, 'optimized_dataset', 'recording_prompts.csv')
OLD_PROMPTS_FILE = os.path.join(DATASET_DIR, 'prompts', 'prompts.csv')

# Use optimized prompts if available, otherwise fall back to old prompts
if os.path.exists(OPTIMIZED_PROMPTS_FILE):
    PROMPTS_FILE = OPTIMIZED_PROMPTS_FILE
    print(f"✓ Using optimized dataset prompts: {OPTIMIZED_PROMPTS_FILE}")
else:
    PROMPTS_FILE = OLD_PROMPTS_FILE
    print(f"⚠ Optimized dataset not found, using: {OLD_PROMPTS_FILE}")
    print(f"  Run 'python optimize_dataset.py' to generate optimized prompts")

METADATA_FILE = os.path.join(RECORDINGS_DIR, 'metadata.jsonl')

# Create directories
os.makedirs(RECORDINGS_DIR, exist_ok=True)


def load_prompts():
    """Load prompts from CSV file."""
    prompts = []
    if os.path.exists(PROMPTS_FILE):
        with open(PROMPTS_FILE, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Ensure all fields exist (handle different CSV formats)
                prompt = {
                    'prompt_id': row.get('prompt_id', ''),
                    'text': row.get('text', ''),
                    'status': row.get('status', 'pending'),
                    'type': row.get('type', 'sentence')  # Default to 'sentence' if not present
                }
                prompts.append(prompt)
    return prompts


def save_prompts(prompts):
    """Save prompts to CSV file."""
    if prompts:
        with open(PROMPTS_FILE, 'w', encoding='utf-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['prompt_id', 'type', 'text', 'status'])
            writer.writeheader()
            writer.writerows(prompts)


def get_audio_duration(filepath):
    """Get duration of audio file in seconds."""
    try:
        with wave.open(filepath, 'rb') as w:
            frames = w.getnframes()
            rate = w.getframerate()
            return frames / float(rate)
    except Exception:
        return None


def is_safe_path(base_dir, path):
    """Check if path is safe (no path traversal)."""
    # Resolve to absolute paths
    base = os.path.abspath(base_dir)
    target = os.path.abspath(path)
    # Ensure target is within base directory
    return target.startswith(base + os.sep) or target == base


def convert_to_wav(input_path, output_path):
    """Convert audio file to WAV format (22kHz, mono, 16-bit optimized for training)."""
    # Validate paths to prevent command injection
    if not is_safe_path(DATASET_DIR, input_path):
        print(f"Security error: Invalid path")
        return False
    
    if not (is_safe_path(DATASET_DIR, output_path) or output_path.startswith('/tmp/')):
        print(f"Security error: Invalid output path")
        return False
    
    try:
        subprocess.run([
            'ffmpeg', '-y', '-i', input_path,
            '-ar', '22050', '-ac', '1', '-c:a', 'pcm_s16le',
            output_path
        ], capture_output=True, check=True)
        return True
    except Exception as e:
        print(f"Conversion error: {e}")
        return False


def append_metadata(metadata):
    """Append metadata to JSONL file."""
    with open(METADATA_FILE, 'a', encoding='utf-8') as f:
        f.write(json.dumps(metadata, ensure_ascii=False) + '\n')


@app.route('/')
def index():
    """Render the modern recording interface."""
    return render_template('recorder_modern.html')


@app.route('/classic')
def classic_index():
    """Render the classic recording interface."""
    return render_template('recorder.html')


@app.route('/api/prompts')
def get_prompts():
    """Get all prompts."""
    prompts = load_prompts()
    return jsonify({
        'ok': True,
        'prompts': prompts,
        'total': len(prompts)
    })


@app.route('/api/prompts/<prompt_id>')
def get_prompt(prompt_id):
    """Get a specific prompt."""
    prompts = load_prompts()
    for prompt in prompts:
        if prompt['prompt_id'] == prompt_id:
            return jsonify({'ok': True, 'prompt': prompt})
    return jsonify({'ok': False, 'error': 'Prompt not found'}), 404


@app.route('/api/prompts/<prompt_id>/status', methods=['POST'])
def update_prompt_status(prompt_id):
    """Update prompt status."""
    data = request.get_json()
    new_status = data.get('status', 'pending')
    
    prompts = load_prompts()
    for prompt in prompts:
        if prompt['prompt_id'] == prompt_id:
            prompt['status'] = new_status
            save_prompts(prompts)
            return jsonify({'ok': True, 'prompt': prompt})
    
    return jsonify({'ok': False, 'error': 'Prompt not found'}), 404


@app.route('/api/save', methods=['POST'])
def save_audio():
    """Save uploaded audio recording."""
    speaker = request.form.get('speaker', 'S01')
    prompt_id = request.form.get('prompt_id', '00000')
    text = request.form.get('text', '')
    prompt_type = request.form.get('type', 'unknown')
    
    audio_file = request.files.get('audio_data')
    if not audio_file:
        return jsonify({'ok': False, 'error': 'No audio data received'})
    
    # Generate filename
    timestamp = datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')
    base_filename = f"{speaker}_{timestamp}_{prompt_id}"
    
    # Use /tmp for temporary file (not in dataset directory)
    with tempfile.NamedTemporaryFile(suffix='.webm', delete=False) as temp_file:
        temp_path = temp_file.name
        audio_file.save(temp_path)
    
    # Final WAV path in recordings directory
    wav_path = os.path.join(RECORDINGS_DIR, f"{base_filename}.wav")
    
    try:
        # Convert to WAV (22kHz mono 16-bit)
        if convert_to_wav(temp_path, wav_path):
            audio_path = wav_path
            filename = f"{base_filename}.wav"
        else:
            # If conversion fails, return error
            return jsonify({'ok': False, 'error': 'Audio conversion failed'})
    finally:
        # Always remove temp file
        if os.path.exists(temp_path):
            os.remove(temp_path)
    
    # Get duration
    duration = get_audio_duration(audio_path) if audio_path.endswith('.wav') else None
    
    # Create metadata
    metadata = {
        'speaker_id': speaker,
        'prompt_id': prompt_id,
        'text': text,
        'type': prompt_type,
        'filename': filename,
        'duration': duration,
        'sample_rate': 22050,  # Training-optimized sample rate
        'bits': 16,
        'accepted': True,
        'timestamp': datetime.utcnow().isoformat()
    }
    
    # Save metadata
    append_metadata(metadata)
    
    # Update prompt status
    prompts = load_prompts()
    for prompt in prompts:
        if prompt['prompt_id'] == prompt_id:
            prompt['status'] = 'done'
            break
    save_prompts(prompts)
    
    return jsonify({
        'ok': True,
        'metadata': metadata,
        'message': f'Saved as {filename}'
    })


@app.route('/api/stats')
def get_stats():
    """Get recording statistics."""
    prompts = load_prompts()
    
    stats = {
        'total_prompts': len(prompts),
        'pending': sum(1 for p in prompts if p.get('status') == 'pending'),
        'done': sum(1 for p in prompts if p.get('status') == 'done'),
        'retry': sum(1 for p in prompts if p.get('status') == 'retry'),
    }
    
    # Count recordings
    recordings = [f for f in os.listdir(RECORDINGS_DIR) if f.endswith('.wav')]
    stats['recordings'] = len(recordings)
    
    # Calculate total duration
    total_duration = 0
    for rec in recordings:
        path = os.path.join(RECORDINGS_DIR, rec)
        dur = get_audio_duration(path)
        if dur:
            total_duration += dur
    
    stats['total_duration_seconds'] = round(total_duration, 2)
    stats['total_duration_minutes'] = round(total_duration / 60, 2)
    
    return jsonify({'ok': True, 'stats': stats})





@app.route('/api/recording/<prompt_id>')
def get_recording(prompt_id):
    """Get a recording by prompt ID."""
    # Search for the recording file
    pattern = os.path.join(RECORDINGS_DIR, f'*_{prompt_id}.wav')
    matches = glob.glob(pattern)
    
    if matches:
        # Return the most recent one
        latest = max(matches, key=os.path.getctime)
        filename = os.path.basename(latest)
        return send_from_directory(RECORDINGS_DIR, filename)
    
    return jsonify({'ok': False, 'error': 'Recording not found'}), 404


@app.route('/api/recording/<prompt_id>', methods=['DELETE'])
def delete_recording(prompt_id):
    """Delete a recording by prompt ID (for re-recording)."""
    # Search for the recording file
    pattern = os.path.join(RECORDINGS_DIR, f'*_{prompt_id}.wav')
    matches = glob.glob(pattern)
    
    deleted_count = 0
    for match in matches:
        if is_safe_path(RECORDINGS_DIR, match):
            try:
                os.remove(match)
                deleted_count += 1
            except OSError:
                pass
    
    # Update prompt status back to pending
    prompts = load_prompts()
    for prompt in prompts:
        if prompt['prompt_id'] == prompt_id:
            prompt['status'] = 'pending'
            break
    save_prompts(prompts)
    
    return jsonify({
        'ok': True,
        'deleted': deleted_count,
        'message': f'Deleted {deleted_count} recording(s)'
    })


@app.route('/recordings/<filename>')
def serve_recording(filename):
    """Serve a recording file."""
    return send_from_directory(RECORDINGS_DIR, filename)


@app.route('/api/quality-check', methods=['POST'])
def check_audio_quality():
    """
    Check audio quality for real-time validation.
    Returns issues like silence-only, clipping, low volume, background noise.
    """
    audio_file = request.files.get('audio_data')
    if not audio_file:
        return jsonify({'ok': False, 'error': 'No audio data received'})
    
    # Use /tmp for temporary files (not in dataset directory)
    with tempfile.NamedTemporaryFile(suffix='.webm', delete=False) as temp_file:
        temp_path = temp_file.name
    with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as wav_file:
        wav_path = wav_file.name
    
    try:
        audio_file.save(temp_path)
        
        # Convert to WAV for analysis
        if not convert_to_wav(temp_path, wav_path):
            return jsonify({'ok': False, 'error': 'Conversion failed'})
        
        # Analyze audio
        issues = []
        quality_score = 100
        
        # Check duration
        duration = get_audio_duration(wav_path)
        if duration is None:
            issues.append('Could not read audio file')
            quality_score -= 50
        elif duration < 0.3:
            issues.append('Recording too short (< 0.3s)')
            quality_score -= 30
        elif duration > 30:
            issues.append('Recording too long (> 30s)')
            quality_score -= 10
        
        # Check for silence-only (using basic analysis)
        if duration and duration > 0:
            try:
                with wave.open(wav_path, 'rb') as w:
                    frames = w.readframes(w.getnframes())
                    # Simple RMS calculation
                    import struct
                    samples = struct.unpack(f'{len(frames)//2}h', frames)
                    rms = (sum(s**2 for s in samples) / len(samples)) ** 0.5 if samples else 0
                    rms_normalized = rms / 32767.0
                    
                    # Check if mostly silence
                    if rms_normalized < 0.01:
                        issues.append('Recording appears to be silence only')
                        quality_score -= 40
                    elif rms_normalized < 0.03:
                        issues.append('Volume is very low')
                        quality_score -= 20
                    
                    # Check for clipping
                    max_sample = max(abs(s) for s in samples) if samples else 0
                    if max_sample >= 32700:
                        issues.append('Audio is clipping (too loud)')
                        quality_score -= 25
            except Exception as e:
                print(f"Audio analysis error: {e}")
        
        return jsonify({
            'ok': True,
            'passed': len(issues) == 0,
            'issues': issues,
            'quality_score': max(0, quality_score),
            'duration': duration
        })
        
    except Exception as e:
        return jsonify({'ok': False, 'error': str(e)})
    finally:
        # Always clean up temp files
        if os.path.exists(temp_path):
            os.remove(temp_path)
        if os.path.exists(wav_path):
            os.remove(wav_path)


@app.route('/api/prompts/navigate', methods=['POST'])
def navigate_prompts():
    """
    Navigate to a specific prompt or find next/previous pending prompt.
    """
    data = request.get_json()
    action = data.get('action', 'next')  # 'next', 'prev', 'goto', 'next_pending'
    current_index = data.get('current_index', 0)
    target_index = data.get('target_index', 0)
    
    prompts = load_prompts()
    if not prompts:
        return jsonify({'ok': False, 'error': 'No prompts loaded'})
    
    if action == 'next':
        new_index = min(current_index + 1, len(prompts) - 1)
    elif action == 'prev':
        new_index = max(current_index - 1, 0)
    elif action == 'goto':
        new_index = max(0, min(target_index, len(prompts) - 1))
    elif action == 'next_pending':
        # Find next pending prompt
        new_index = current_index
        for i in range(current_index + 1, len(prompts)):
            if prompts[i].get('status') == 'pending':
                new_index = i
                break
        else:
            # Wrap around to beginning
            for i in range(0, current_index):
                if prompts[i].get('status') == 'pending':
                    new_index = i
                    break
    else:
        new_index = current_index
    
    # Get context (previous and next prompts for preview)
    context = {
        'previous': prompts[new_index - 1] if new_index > 0 else None,
        'current': prompts[new_index],
        'next': prompts[new_index + 1] if new_index < len(prompts) - 1 else None,
    }
    
    return jsonify({
        'ok': True,
        'index': new_index,
        'total': len(prompts),
        'context': context
    })





if __name__ == '__main__':
    print("\n" + "=" * 60)
    print("🎙️  Bengali TTS Studio - Professional Recording Server")
    print("=" * 60)
    print(f"\n📁 Dataset directory: {DATASET_DIR}")
    print(f"📁 Recordings directory: {RECORDINGS_DIR}")
    print(f"📁 Prompts file: {PROMPTS_FILE}")
    print(f"🎵 Audio format: 22kHz, mono, 16-bit PCM (optimized for training)")
    
    # Check if prompts exist
    prompts = load_prompts()
    if not prompts:
        print("\n⚠️  No prompts found! Run 'python generate_prompts.py' first.")
    else:
        print(f"\n✓ Loaded {len(prompts)} prompts")
    
    print("\n🌐 Modern UI: http://localhost:5000")
    print("🌐 Classic UI: http://localhost:5000/classic")
    print("\nPress Ctrl+C to stop\n")
    print("=" * 60 + "\n")
    
    # Note: Set debug=False in production environments
    import sys
    debug_mode = '--debug' in sys.argv
    app.run(host='0.0.0.0', port=5000, debug=debug_mode)
